### ISSUE TITLE
"ready" is always false

### ISSUE THREAD

**Issue by MarcusHSmith** [tellerhq/teller-connect-react#5]
I'm implementing `teller-connect-react` in my NextJS 13 app.

```
  const { open, ready } = useTellerConnect({
    appId: 'app_on5...0',
    onSuccess: (authorization: any) => {
      // Save your access token here
      console.log('ON SUCCESS', authorization)
    },
  })

  console.log('READY', ready)

  return (
```

Ready is always `false`. Any advice?

**Comment by andycodesstuff** [comment]
Hi @MarcusHSmith, thanks for reporting the issue. I'll investigate the matter and get back to you asap (;

**Comment by MarcusHSmith** [comment]
Upgrading from `0.0.1` to `0.1.0` solved the issue. Thanks
